require 'aws-sdk'
require 'active_support/all'

$LOAD_PATH.unshift( File.expand_path( '..', File.dirname( __FILE__ ) ) )
require 'lib/boxxspring/abstract'
require 'lib/boxxspring/journal'
require 'lib/boxxspring/worker/configuration'
require 'lib/boxxspring/worker/base'
require 'lib/boxxspring/worker/task_base'
require 'lib/boxxspring/worker/activist_task_base'
require 'lib/boxxspring/synchronization/configuration'
require 'lib/boxxspring/synchronization'
require 'lib/boxxspring/synchronization/operations'
require 'lib/boxxspring/synchronization/orchestrator'
require 'lib/boxxspring/synchronization/mutex'
require 'lib/boxxspring/synchronization/variable'